import { WithoutSystemFields } from "convex/server";
import { Doc } from "./_generated/dataModel";
import { internalMutation, type MutationCtx } from "./_generated/server";

const seedUsers: WithoutSystemFields<Doc<"users">>[] = [
  {
    name: "Alex Morgan",
    email: "alex.morgan@example.com",
    bio: "Love hiking and photography. Looking for someone to explore the city with!",
    birthDate: "1995-03-15T00:00:00Z",
    height: { value: 175, unit: "cm" },
    weight: { value: 70, unit: "kg" },
    bodyTypes: ["athletic"],
    orientation: "gay",
    lookingFor: ["dating", "connections"],
    position: ["versatile"],
    ethnicity: ["white"],
    profilePictures: [],
    hasCompletedOnboarding: true,
    privacy: {
      hideDistance: false,
      hideAge: false,
      hideOnlineStatus: false,
      hideProfileFromDiscovery: false,
    },
  },
  {
    name: "Jordan Kim",
    email: "jordan.kim@example.com",
    bio: "Coffee enthusiast and bookworm. Always up for a good conversation.",
    birthDate: "1998-07-22T00:00:00Z",
    height: { value: 168, unit: "cm" },
    weight: { value: 65, unit: "kg" },
    bodyTypes: ["slim"],
    orientation: "bisexual",
    lookingFor: ["friends", "dating"],
    position: ["top"],
    ethnicity: ["asian"],
    profilePictures: [],
    hasCompletedOnboarding: true,
    privacy: {
      hideDistance: false,
      hideAge: true,
      hideOnlineStatus: false,
      hideProfileFromDiscovery: false,
    },
  },
  {
    name: "Sam Taylor",
    email: "sam.taylor@example.com",
    bio: "Fitness enthusiast and travel lover. Let's go on adventures together!",
    birthDate: "1992-11-08T00:00:00Z",
    height: { value: 180, unit: "cm" },
    weight: { value: 85, unit: "kg" },
    bodyTypes: ["muscular"],
    orientation: "gay",
    lookingFor: ["dating"],
    position: ["versatile", "top"],
    ethnicity: ["mixed"],
    profilePictures: [],
    hasCompletedOnboarding: true,
    privacy: {
      hideDistance: false,
      hideAge: false,
      hideOnlineStatus: true,
      hideProfileFromDiscovery: false,
    },
  },
  {
    name: "Riley Chen",
    email: "riley.chen@example.com",
    bio: "Artist and music lover. Looking for creative connections.",
    birthDate: "1996-05-30T00:00:00Z",
    height: { value: 172, unit: "cm" },
    weight: { value: 68, unit: "kg" },
    bodyTypes: ["average"],
    orientation: "lesbian",
    lookingFor: ["friends", "connections"],
    position: ["side"],
    ethnicity: ["asian"],
    profilePictures: [],
    hasCompletedOnboarding: true,
    privacy: {
      hideDistance: true,
      hideAge: false,
      hideOnlineStatus: false,
      hideProfileFromDiscovery: false,
    },
  },
  {
    name: "Casey Martinez",
    email: "casey.martinez@example.com",
    bio: "Foodie and wine enthusiast. Let's discover new restaurants together!",
    birthDate: "1994-09-12T00:00:00Z",
    height: { value: 165, unit: "cm" },
    weight: { value: 62, unit: "kg" },
    bodyTypes: ["slim", "athletic"],
    orientation: "bisexual",
    lookingFor: ["dating", "friends"],
    position: ["bottom"],
    ethnicity: ["latinoHispanic"],
    profilePictures: [],
    hasCompletedOnboarding: true,
    privacy: {
      hideDistance: false,
      hideAge: false,
      hideOnlineStatus: false,
      hideProfileFromDiscovery: false,
    },
  },
  {
    name: "Morgan Davis",
    email: "morgan.davis@example.com",
    bio: "Tech geek and gaming enthusiast. Always up for a challenge!",
    birthDate: "1997-01-25T00:00:00Z",
    height: { value: 178, unit: "cm" },
    weight: { value: 75, unit: "kg" },
    bodyTypes: ["average", "athletic"],
    orientation: "gay",
    lookingFor: ["connections", "friends"],
    position: ["top", "versatile"],
    ethnicity: ["white", "mixed"],
    profilePictures: [],
    hasCompletedOnboarding: true,
    privacy: {
      hideDistance: false,
      hideAge: false,
      hideOnlineStatus: false,
      hideProfileFromDiscovery: false,
    },
  },
  {
    name: "Taylor Johnson",
    email: "taylor.johnson@example.com",
    bio: "Yoga instructor and wellness advocate. Seeking meaningful connections.",
    birthDate: "1993-06-18T00:00:00Z",
    height: { value: 170, unit: "cm" },
    weight: { value: 64, unit: "kg" },
    bodyTypes: ["slim", "athletic"],
    orientation: "lesbian",
    lookingFor: ["dating"],
    position: ["versatile"],
    ethnicity: ["white"],
    profilePictures: [],
    hasCompletedOnboarding: true,
    privacy: {
      hideDistance: false,
      hideAge: true,
      hideOnlineStatus: false,
      hideProfileFromDiscovery: false,
    },
  },
  {
    name: "Jamie Williams",
    email: "jamie.williams@example.com",
    bio: "Outdoor adventurer and nature photographer. Let's explore together!",
    birthDate: "1991-12-05T00:00:00Z",
    height: { value: 182, unit: "cm" },
    weight: { value: 88, unit: "kg" },
    bodyTypes: ["muscular", "athletic"],
    orientation: "gay",
    lookingFor: ["dating", "friends"],
    position: ["top"],
    ethnicity: ["black"],
    profilePictures: [],
    hasCompletedOnboarding: true,
    privacy: {
      hideDistance: false,
      hideAge: false,
      hideOnlineStatus: false,
      hideProfileFromDiscovery: false,
    },
  },
  {
    name: "Avery Brown",
    email: "avery.brown@example.com",
    bio: "Writer and poet. Looking for someone who appreciates the arts.",
    birthDate: "1999-04-20T00:00:00Z",
    height: { value: 160, unit: "cm" },
    weight: { value: 58, unit: "kg" },
    bodyTypes: ["slim"],
    orientation: "bisexual",
    lookingFor: ["connections", "friends"],
    position: ["askMe"],
    ethnicity: ["white", "asian"],
    profilePictures: [],
    hasCompletedOnboarding: true,
    privacy: {
      hideDistance: true,
      hideAge: false,
      hideOnlineStatus: true,
      hideProfileFromDiscovery: false,
    },
  },
  {
    name: "Quinn Anderson",
    email: "quinn.anderson@example.com",
    bio: "Chef and food blogger. Always experimenting with new recipes!",
    birthDate: "1996-08-14T00:00:00Z",
    height: { value: 175, unit: "cm" },
    weight: { value: 72, unit: "kg" },
    bodyTypes: ["average", "stocky"],
    orientation: "gay",
    lookingFor: ["dating"],
    position: ["bottom", "versatile"],
    ethnicity: ["mixed"],
    profilePictures: [],
    hasCompletedOnboarding: true,
    privacy: {
      hideDistance: false,
      hideAge: false,
      hideOnlineStatus: false,
      hideProfileFromDiscovery: false,
    },
  },
];

export default internalMutation({
  handler: async (ctx: MutationCtx) => {
    // If this project already has a populated database, do nothing
    const anyUser = await ctx.db.query("users").first();
    if (anyUser) return;

    // Insert each seed user
    for (const userData of seedUsers) {
      await ctx.db.insert("users", userData);
    }
  },
});
